[project]
name = "verbs-play-bot"
version = "0.1.0"
description = "Verbs Play Customer Service Bot"
requires-python = ">=3.13"
dependencies = [
    "editorconfig-checker>=3.4.0",
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.5",
    "ruff>=0.14.0",
]
